version: '3'

services:
  reverse-proxy:
    build: traefik
    command: --api
    ports:
      - "80:80"     # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
    networks:
      - traefik
    labels:
      - "traefik.backend=traefik"


networks:
  traefik:
