version: '3'

services:
  whoami1:
    image: emilevauge/whoami # A container that exposes an API to show its IP address
    networks:
      - traefik-test_traefik
    labels:
      - "traefik.domain=whoami.test"
      - "traefik.backend=whoami"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=PathPrefix:/findme"

  whoami2:
    image: emilevauge/whoami # A container that exposes an API to show its IP address
    networks:
      - traefik-test_traefik
    labels:
      - "traefik.domain=whoami.test"
      - "traefik.backend=whoami"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=PathPrefix:/findme"

networks:
  traefik-test_traefik:
    external: true
