logLevel = "DEBUG"
defaultEntryPoints = ["http", "https"]

[api]
    debug = true

[entryPoints]
    [entryPoints.traefik]
    address = ":8080"

    [entryPoints.traefik.auth.basic]
    users = ["admin:$apr1$hD9OJEta$TT7mPGXzdnkKXY/zfmFLm0"]

    [entryPoints.http]
    address = ":80"

    [entryPoints.https]
    address = ":443"
        [entryPoints.https.tls]
            [[entryPoints.https.tls.certificates]]
            certFile = "/certs/cert.crt"
            keyFile = "/certs/cert.key"

    [entryPoints.withTLS]
    address = ":4443"
        [entryPoints.withTLS.tls.ClientCA]
        files = ["/certs/client.crt"]
        optional = false
        [entryPoints.withTLS.tls]
            [[entryPoints.withTLS.tls.certificates]]
            certFile = "/certs/cert.crt"
            keyFile = "/certs/cert.key"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.localhost"

watch = true

exposedByDefault = true